### ISSUE TITLE
Publish as Hex package

### ISSUE THREAD

**Issue by danxexe** [bradleyd/exgrid#2]
Did you consider publishing to Hex? https://hex.pm/docs/publish

**Comment by bradleyd** [comment]
@danxexe you mind giving a second set of eyes here
https://hex.pm/packages/exgrid

**Comment by bradleyd** [comment]
I agree.  I updated the [readme](https://github.com/bradleyd/exgrid/blob/master/README.md) to reflect this.  
As for the community package, I think it is a good idea.

Thanks again,
Brad

**Comment by cloudbring** [comment]
@bradleyd @danxexe Any word on the community package?

If needed / wanted, I could create a community package for ibrowse so exgrid could be packaged  through hex.

**Comment by bradleyd** [comment]
@cloudbring I have not built a ibrowse package as of yet.  I did jump on hex.pm and no dice as of today.  I will try to carve out sometime to investigate creating one.

**Comment by cloudbring** [comment]
As I said, I'd be happy to help. I'm planning on using this for an upcoming
project.

**Comment by bradleyd** [comment]
That would be great!! @cloudbring
