### ISSUE TITLE
Tests Failing Due to Bad SendGrid Credentials

### ISSUE THREAD

**Issue by cloudbring** [bradleyd/exgrid#4]
![image](https://cloud.githubusercontent.com/assets/22373/7904685/882569cc-07ba-11e5-8ae6-ae29c6fa6c24.png)
### We should fix the failing tests with some account help from @SendGrid
- I'm sure some of my old friends there (@brandonmwest @iandouglas @ben-grid @thinkingserious @siyegen) might be able to help out this SendGrid plugin for [Elixir](https://github.com/elixir-lang/elixir) / [Website](http://elixir-lang.org) and [PhoenixFramework](https://github.com/phoenixframework/phoenix) / [Website](http://www.phoenixframework.org)
- **If someone could get @bradleyd an account credit so he could login and keep the tests passing, that'd be great**

As far as I can see, the tests just validate that credentials can login. It doesn't send any email.

**Comment by bradleyd** [comment]
@cloudbring I waffled on the integration tests vs mocking the http calls.  I could not decide and got pulled in another direction.  I cringe a little to have a sendgrid test account to run these tests.  With that said, I am completely open to a better approach ;)  
There are tools--now--that may be worth the investment such as [exvcr](https://github.com/parroty/exvcr)
or [mock](https://github.com/jjh42/mock)

**Comment by bradleyd** [comment]
I have removed the integration tests.  I have replaced them with unit mocks.

**Comment by thinkingserious** [comment]
Hi @bradleyd,

You can now use prism via stoplight.io in combination with our Open API specification to mock out all SendGrid API calls. [Here](https://github.com/sendgrid/sendgrid-java/blob/master/CONTRIBUTING.md#testing) is an example.

With Best Regards,

Elmer
