### ISSUE TITLE
A few tests failing after my updates

### ISSUE THREAD

**Issue by katgironpe** [bradleyd/exgrid#6]
Hi! Quick intro on why I use this: I need this ASAP for 3 projects. 

I made efforts to fix some failing tests here:
https://github.com/katgironpe/exgrid

There are still about 5 failing tests due to request timeout issues.

`(HTTPotion.HTTPError) req_timedout`

I think what I need is working now, except for some features. You might want to check it out. 

Thank you!

**Comment by bradleyd** [comment]
Thanks! I am aware of the tests failing.  They were using my old account.  A re-write of the tests is on the list.

**Comment by katgironpe** [comment]
Good to know.

**Comment by bradleyd** [comment]
I am closing this issue.  I have not seen the time out happen.  Please re-open if it comes back up again with some details.  Thanks for communicating this!
